# Generated by Django 5.2.8 on 2025-12-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
