# Generated by Django 5.2.8 on 2025-12-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_image_url_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Produk Terbaru',
                'verbose_name_plural': 'Produk Terbaru',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
    ]
