# Generated by Django 5.2.8 on 2025-12-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_latestproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latestproduct',
            options={},
        ),
    ]
