# Generated by Django 5.2.8 on 2025-12-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business_entity_type',
            field=models.CharField(blank=True, choices=[('pt', 'PT'), ('cv', 'CV'), ('ud', 'UD'), ('firma', 'Firma'), ('koperasi', 'Koperasi'), ('yayasan', 'Yayasan'), ('instansi', 'Instansi Pemerintah'), ('lainnya', 'Lainnya')], help_text='Isi hanya jika customer adalah perusahaan', max_length=50, null=True),
        ),
    ]
